name: Test on Windows

on:
  workflow_dispatch:

jobs:
  default:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test
